### PR TITLE
Update PhotonIDisoProducer.cc

### PR DESCRIPTION
**Pull request by bmahakud**
I have updated the code with latest 13TeV Egamma Effective areas and corresponding recommended cuts

### CODE REVIEW

**Comment by adrager** [comment]
Dear all,

I just did a pull of the latest version. And I get some compiler error

JetCleaner.cc

invalid use of incomplete type 'class edm::EDProducer'

Could you please have a look?

Cheers,

Arne

**Comment by adrager** [comment]
On 06/02/2015 11:15 PM, Andrew Whitbeck wrote:
>
> Merged #6 <https://github.com/TreeMaker/TreeMaker/pull/6>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TreeMaker/TreeMaker/pull/6#event-320508982>.
>
ok i found the bug. fixed it...

**Comment by awhitbeck** [comment]
Hi Arne,

what was the bug?  I didn't have any problems compiling the code.

Andrew

**Comment by adrager** [comment]
Hi Andrew,

there was an include missing.
#include "FWCore/Framework/interface/EDProducer.h"

Arne

**Comment by awhitbeck** [comment]
Hmm interesting, thanks for fixing it!

Andrew

**Pull request merged**
