### PR TITLE
Remove JER smearing from energy fractions and MHT fix

### PR DESCRIPTION
**Pull request by kpedro88**

### CODE REVIEW

**Comment by aperloff** [comment]
Looks good to me. Did you check that if you draw, for example, the chargeHadronEnergyFraction that none of the values go beyond 1? This was happening more for low pt jets with some regularity, but you would need to do it for more than 100 events, so I would plan on testing it with 1000 or 10000 events.

**Comment by kpedro88** [comment]
I had only tested with 100 events. I will run a larger test.

**Comment by kpedro88** [comment]
Confirmed with 10K events that all fractions are < 1.

**Comment by aperloff** [comment]
Okay I approve. Or in the parlance of cms-sw/cmssw...+1

**Pull request merged**
