### PR TITLE
Updated trigger list for 2017

### PR DESCRIPTION
**Pull request by aperloff**
Inputs from Nadja, Scarlet, Kevin, Owen, Andrew, and Vinay.

Not sure if you want to merge this in now or wait for future emails to trickle in. I can either continuously update the PR or open a new PR.

### CODE REVIEW

**Comment by kpedro88** [comment]
I think we might as well leave it open for a while to see if we get more trigger requests.

**Comment by aperloff** [comment]
I have not received any more emails for trigger requests. I think it's probably safe to merge this in. I can always do another PR in the future.

**Comment by kpedro88** [comment]
Can you add the ones @nstrobbe requested in #274?

**Comment by aperloff** [comment]
Triggers from #274 added.

**Pull request merged**
