### PR TITLE
beam halo filter recommended in early 2017 data

### PR DESCRIPTION
**Pull request by tmulholland**
https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#Early_2017_data

### CODE REVIEW

**Comment by kpedro88** [comment]
@tmulholland thanks; did you run a test with 2017 data to make sure the branch is filled sensibly?

**Comment by tmulholland** [comment]
No, I have not. I'll run a quick test and report back the results.

**Comment by kpedro88** [comment]
@tmulholland results?

**Comment by kpedro88** [comment]
@tmulholland ping

**Pull request closed without merging**
