### PR TITLE
[Run2_2017] Getting ready to run on the 2018 data

### PR DESCRIPTION
**Pull request by aperloff**
This PR updates the Run2_2017 branch for processing the 2018 data. It includes the necessary dictionaries, file lists, scenarios, unit tests, and readme. There is also a small update to get_mcm.py.

### CODE REVIEW

**Comment by kpedro88** [comment]
Is all of the 2018 re-reco done now? I though some samples were still processing.

**Comment by aperloff** [comment]
They paused the processing and told us to run on what was there. The time to completion is at least several months.

**Comment by kpedro88** [comment]
Okay... this is going to be a huge pain in the ass for file lists, because when we regenerate them, the order will change.

**Comment by aperloff** [comment]
Nothing I can do about that. We could institute some sorting.

**Comment by kpedro88** [comment]
The file lists are sorted, but the missing files could appear anywhere. I guess we'll burn that bridge after we jump off it.

**Pull request merged**
