### PR TITLE
Run2 2017

### PR DESCRIPTION
**Pull request by rpatelCERN**
Hey Kevin, 

Here are a few updates from the previous pull:

1) New JSON file
2) A few updates for the trigger path lists
3) I am not sure why it says my AllHadronicSUSY/Utils/python/trackIsolationMaker_cfi.py is different from yours. I also removed the PATCandViewCountFilter, but it still comes up in this PR? Not sure why

### CODE REVIEW

**Comment by kpedro88** [comment]
@rpatelCERN I think you started from a weird branch or something... the "AllHadronicSUSY" folder hasn't been used in years, and I see a very old commit from @awhitbeck in your branch.

Other followup items from #236 include adding 2017B-v1 to the condor dictionary and the lumiSummary dictionary. Please include those in this PR.

**Comment by kpedro88** [comment]
@rpatelCERN you need to fix this branch to remove the unwanted commit

**Comment by rpatelCERN** [comment]
Hey Kevin, I added the dictionary in the latest commit. How do I remove the weird commit from Andrew?
-Rishi

**Comment by rpatelCERN** [comment]
Oh sorry I see what you mean, there is a weird AllHadronicSUSY folder.
-Rishi

**Comment by kpedro88** [comment]
I don't really understand how it got in there in the first place, so I would just start over and cherry pick your changes:
```
git fetch upstream
git branch -m Run2_2017 Run2_2017_backup
git checkout -b Run2_2017 upstream/Run2_2017
git cherry-pick db163a1
git cherry-pick 4f16f28
git cherry-pick 81cbed3
git cherry-pick 7d35ac9
git push -f origin Run2_2017
```

You also still need to update dataSamples.py.

**Comment by kpedro88** [comment]
@rpatelCERN I prefer to remove the errant commit entirely following the procedure outlined above

**Comment by rpatelCERN** [comment]
I added the modified dataSamples.py .
-Rishi

**Comment by kpedro88** [comment]
@rpatelCERN you also need to sync with upstream to resolve this merge conflict (#237 already made an update to dataSamples.py)

**Comment by kpedro88** [comment]
@rpatelCERN not sure what you did, but I guess this PR needs to be remade now
(your commits still exist on GitHub in case you lost them locally)

**Pull request closed without merging**
