### PR TITLE
[Run2_UL] Minimal changes to add and ntuplize a single UL sample

### PR DESCRIPTION
**Pull request by aperloff**
The PR implements the minimal changes needed to produce an ntuple for a single ultra legacy sample. Many of the changes needed to produce a valid ntuple (i.e. updated JEC/JER, updated cross sections) were not implemented here. These will be implemented in future PRs. The list of changes is as follows:
1. Add a scenario for 'Summer20UL18' samples
2. Add the file list for a single Summer20UL18 sample
3. Add the necessary weightProducer line
4. Add a unit test
5. Add a dictionary for condor production
6. Some additional changes needed when moving from CMSSW_10_2_X to CMSSW_10_6_X. For example, the `associateTask` option was removed from the JetToolbox. Now we use the `outputFile` option with `'noOutput'` to avoid creating the `jettoolbox.root` file.
7. Move from CMSSW_10_6_20_patch1 to CMSSW_10_6_25.

### CODE REVIEW

**Comment by kpedro88** [comment]
1. It looks like this feature was modified several times. The latest version requires setting `outputFile='noOutput'` as described at https://github.com/cms-jet/JetToolbox/pull/69.
2. Seems fine to me.

**Comment by aperloff** [comment]
@kpedro88 Sorry for the last minute updates. It's ready for review now.

**Comment by kpedro88** [comment]
Looks fine to me.

**Comment by kpedro88** [comment]
Do we need to modify the CI setup so that it runs for PRs to the `Run2_UL` branch?

**Comment by aperloff** [comment]
Good call. I have added some changes to the CI files which will run the CI jobs.

**Comment by aperloff** [comment]
@kpedro88 I have updated the standalone [CMSSW image](https://hub.docker.com/layers/treemaker/cmssw/CMSSW_10_6_25-2021-05-20-563715a3/images/sha256-db4590e8a0aebbfe5e71b0c446be9f09744130725673cdd78d23fd2d97b08c3a?context=repo) and I can confirm that the lightweight build and integration checks (GitHub actions) are successful. I think this is ready to be merged. Do you concur?

**Comment by kpedro88** [comment]
+1

**Pull request merged**
