### PR TITLE
Adding TTJets and GJets Samples

### PR DESCRIPTION
**Pull request by JHiltbrand**
--add in all available, relevant TTJets samples
--add in one missing GJet HT bin for 2016

N.B. There is no LO inclusive TTJets sample to use for calculating a k factor.

### CODE REVIEW

**Comment by JHiltbrand** [comment]
Hey @kpedro88 and @cmadrid1,

For the DiLept and SingleLept TTJets samples, I see there are samples with and without a `genMET` cut. Do you prefer to have both versions, or one or the other ? Just finishing up on TTJets for this PR, since all years seem complete.

**Comment by kpedro88** [comment]
Please include both. Thanks!

**Comment by kpedro88** [comment]
@JHiltbrand can you check for TTJets_SingleLeptFromTbar_genMET-150_TuneCP5_13TeV-madgraphMLM-pythia8 in 18UL? That seems to be the only one that is still missing from this PR. Thanks!

**Comment by JHiltbrand** [comment]
> @JHiltbrand can you check for TTJets_SingleLeptFromTbar_genMET-150_TuneCP5_13TeV-madgraphMLM-pythia8 in 18UL? That seems to be the only one that is still missing from this PR. Thanks!

Alright, added it in and merged in `Run2_UL`

**Pull request merged**
