### PR TITLE
P uweights commit

### PR DESCRIPTION
**Pull request by rpatelCERN**
Hey Kevin, 
Here is the pull request just submitting the PU weights and the input PU weights file from Jack.

-Rishi

### CODE REVIEW

**Comment by kpedro88** [comment]
@rpatelCERN - this looks fine to me. I'm wondering, though, whether we should test it on some sample to make sure the weighting works as expected. Could you or @jbradmil check this?

**Comment by rpatelCERN** [comment]
Hey Kevin, 
I can check it for a signal point. I actually realized that there is one line I need to change in the WeightProducer. You cancel the previous pull request.  
-Rishi

**Comment by kpedro88** [comment]
@rpatelCERN - you can just push your change to this branch in your remote and it will automatically update the pull request.

**Comment by rpatelCERN** [comment]
sorry I just read that on the gist. I can just push the change.

**Comment by rpatelCERN** [comment]
For the weighting, I ran over a few events and looked at the nominal NVtx (line) and the reweighed (markers). I think it looks reasonable:

**Comment by kpedro88** [comment]
@rpatelCERN - okay, thanks. Did you intend to attach a plot to your previous comment? If so, it didn't come through...

**Pull request merged**
