### PR TITLE
Added flag for adding photon information

### PR DESCRIPTION
**Pull request by yimuchen**
When running the TreeMaker, one can add the option `doPhotons=True` to force the addition of photon variables. 
The corresponding variables is also added using the same routine with the `doZinv=True` flag

### CODE REVIEW

**Comment by kpedro88** [comment]
thanks @yimuchen ! @lwang046 before we merge this, can you check that the photon ID and isolation working points we use by default are adequate for what you want to do?

**Comment by yimuchen** [comment]
All the mechanicse are there, with the difference being that the 2018 paper uses the medium working points, while the default cut values in TreeMaker uses the loose working point. We are not actually using the photons for any computation, just as an offline signal rejection target, so maybe changing working points doesn't matter much?

**Comment by kpedro88** [comment]
Right; we can always apply a tighter working point offline, as long as all the ingredients are there.

**Comment by lwang046** [comment]
It seems indeed all the ingredients needed according to this [twiki](https://twiki.cern.ch/twiki/bin/view/CMS/CutBasedPhotonIdentificationRun2) are there.

**Comment by yimuchen** [comment]
Pull request submitted: https://github.com/TreeMaker/TreeMaker/pull/569

**Pull request merged**
